name: MY CI Checks

on: [push, pull_request, workflow_dispatch]

jobs:
  # Python Dependency Installation and Tests
  python_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: |
          if [ -f "tests/"]; then pytest; fi

  # File Name Linting
  ls_linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ls-lint/action@v2.2.3

  # Markdown File Linting
  md_linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          globs: '**/*.md'
